# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mumma
tagline:             'Patrik Gustafsson (Paven) - Blog'
description:         'This is i my main blog, that includes blogg post from my themed blogs'
url:                 http://blog.mumma.nu
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Patrik Gustafsson
  url:               https://twitter.com/paven
  email:             blog@mumma.nu

# Custom vars
version:             1.0.0
